### ISSUE TITLE
Empty smiles string causes errors

### ISSUE THREAD

**Issue by tdudgeon** [InformaticsMatters/pipelines-utils-rdkit#1]
When parsing a data that has no value (empty string) for the smiles the rdkit molecule parsing blows up.
Would probably also happen for mol format.
The faulty code is here: https://github.com/InformaticsMatters/pipelines-utils-rdkit/blob/master/src/python/pipelines_utils_rdkit/rdkit_utils.py#L287-L289

In case of the empty string `None` should be returned as the molecule.

**Comment by alanbchristie** [comment]
Better handling of both my_type and txt committed to master branch. If either is `None` or empty then `None` is returned.
